/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const QnaLazyImport = createFileRoute('/qna')()
const DataLazyImport = createFileRoute('/data')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const QnaLazyRoute = QnaLazyImport.update({
  path: '/qna',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/qna.lazy').then((d) => d.Route))

const DataLazyRoute = DataLazyImport.update({
  path: '/data',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/data.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataLazyImport
      parentRoute: typeof rootRoute
    }
    '/qna': {
      id: '/qna'
      path: '/qna'
      fullPath: '/qna'
      preLoaderRoute: typeof QnaLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  DataLazyRoute,
  QnaLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/data",
        "/qna"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/data": {
      "filePath": "data.lazy.tsx"
    },
    "/qna": {
      "filePath": "qna.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
